// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationExecutionAPI.Data;

#nullable disable

namespace MigrationExecutionAPI.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260901220802_UpdateModelsForGovernanceAndLlm")]
    partial class UpdateModelsForGovernanceAndLlm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MigrationExecutionAPI.Models.ApprovalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionOverridePrompt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("ApprovalRecords");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.FileChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacementContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("FileChanges");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.JobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("JobLogs");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.LlmUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("LlmUsageLogs");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.MigrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBranchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionReport")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MergeCommitSha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevertPrUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFramework")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCommit")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFramework")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("MigrationJobs");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.MigrationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Replacement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MigrationRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Migrate from Startup.cs to Program.cs minimal hosting",
                            IsActive = true,
                            Pattern = "UseStartup<Startup>()",
                            Replacement = "builder.Services.AddControllers();",
                            SourceVersion = "net6.0",
                            TargetVersion = "net8.0"
                        });
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 1, 22, 8, 1, 979, DateTimeKind.Utc).AddTicks(8555),
                            Name = "Global Corp"
                        });
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.ProjectProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetFramework")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryProfileId");

                    b.ToTable("ProjectProfiles");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.RepositoryProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalProjects")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId")
                        .IsUnique();

                    b.ToTable("RepositoryProfiles");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Platform Engineering",
                            OrganizationId = 1
                        });
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "hashed_pw_here",
                            Role = "Admin",
                            TeamId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.ApprovalRecord", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.User", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId");

                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithMany("ApprovalRecords")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.FileChange", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithMany("FileChanges")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.JobLog", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithMany("JobLogs")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.LlmUsageLog", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithMany("LlmUsageLogs")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.MigrationJob", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("MigrationExecutionAPI.Models.Team", "Team")
                        .WithMany("MigrationJobs")
                        .HasForeignKey("TeamId");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.ProjectProfile", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.RepositoryProfile", "RepositoryProfile")
                        .WithMany("Projects")
                        .HasForeignKey("RepositoryProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositoryProfile");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.RepositoryProfile", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithOne("RepositoryProfile")
                        .HasForeignKey("MigrationExecutionAPI.Models.RepositoryProfile", "MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.Team", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.User", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.MigrationJob", b =>
                {
                    b.Navigation("ApprovalRecords");

                    b.Navigation("FileChanges");

                    b.Navigation("JobLogs");

                    b.Navigation("LlmUsageLogs");

                    b.Navigation("RepositoryProfile");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.Organization", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.RepositoryProfile", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.Team", b =>
                {
                    b.Navigation("MigrationJobs");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
