// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationExecutionAPI.Data;

#nullable disable

namespace MigrationExecutionAPI.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260901211915_AddMigrationRules")]
    partial class AddMigrationRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MigrationExecutionAPI.Models.FileChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacementContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("FileChanges");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.JobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("JobLogs");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.LlmUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MigrationJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId");

                    b.ToTable("LlmUsageLogs");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.MigrationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBranchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionReport")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MergeCommitSha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MigrationPlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevertPrUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFramework")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCommit")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFramework")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MigrationJobs");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.MigrationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Replacement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MigrationRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Migrate from Startup.cs to Program.cs minimal hosting",
                            IsActive = true,
                            Pattern = "UseStartup<Startup>()",
                            Replacement = "builder.Services.AddControllers();",
                            SourceVersion = "net6.0",
                            TargetVersion = "net8.0"
                        });
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "hashed_pw_here",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.FileChange", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithMany("FileChanges")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.JobLog", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithMany("JobLogs")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.LlmUsageLog", b =>
                {
                    b.HasOne("MigrationExecutionAPI.Models.MigrationJob", "MigrationJob")
                        .WithMany("LlmUsageLogs")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("MigrationExecutionAPI.Models.MigrationJob", b =>
                {
                    b.Navigation("FileChanges");

                    b.Navigation("JobLogs");

                    b.Navigation("LlmUsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
