using Octokit;
using System.Text.RegularExpressions;

namespace MigrationExecutionAPI.Services;

public class GitHubService
{
    private readonly string _appName = "MigrationDashboardApp";

    private GitHubClient GetClient(string token)
    {
        return new GitHubClient(new ProductHeaderValue(_appName))
        {
            Credentials = new Credentials(token)
        };
    }

    public async Task<IReadOnlyList<Repository>> GetUserRepositoriesAsync(string token)
    {
        var client = GetClient(token);
        return await client.Repository.GetAllForCurrent();
    }

    public async Task<IReadOnlyList<Branch>> GetBranchesAsync(string token, string owner, string repoName)
    {
        var client = GetClient(token);
        return await client.Repository.Branch.GetAll(owner, repoName);
    }

    public async Task<IReadOnlyList<GitHubCommit>> GetRecentCommitsAsync(string token, string owner, string repoName, string? branchSha = null)
    {
        var client = GetClient(token);
        // Get last 20 commits
        var request = new CommitRequest();
        if (!string.IsNullOrEmpty(branchSha))
        {
            request.Sha = branchSha;
        }
        var allCommits = await client.Repository.Commit.GetAll(owner, repoName, request);
        return allCommits.Take(20).ToList();
    }

    public async Task<GitHubCommit> GetCommitAsync(string token, string owner, string repoName, string sha)
    {
        var client = GetClient(token);
        return await client.Repository.Commit.Get(owner, repoName, sha);
    }

    public async Task<(string BranchName, string PrUrl, string CommitHash)> CreatePullRequestAsync(
        string token, 
        string owner, 
        string repoName, 
        string branchName, 
        string commitMessage, 
        List<(string FilePath, string Content)> fileChanges,
        string? targetBranch = null)
    {
        var client = GetClient(token);

        // 1. Get the target branch and its latest commit
        var repo = await client.Repository.Get(owner, repoName);
        var baseBranch = !string.IsNullOrEmpty(targetBranch) ? targetBranch : repo.DefaultBranch;
        var baseBranchRef = await client.Git.Reference.Get(owner, repoName, $"heads/{baseBranch}");

        // 2. Create a new branch
        var newBranchRef = $"refs/heads/{branchName}";
        await client.Git.Reference.Create(owner, repoName, new NewReference(newBranchRef, baseBranchRef.Object.Sha));

        // 3. Get the latest tree
        var latestCommit = await client.Git.Commit.Get(owner, repoName, baseBranchRef.Object.Sha);
        var baseTreeSha = latestCommit.Tree.Sha;

        // 4. Create blobs for the modified files
        var newTreeItem = new List<NewTreeItem>();
        foreach (var file in fileChanges)
        {
            var blob = new NewBlob { Encoding = EncodingType.Utf8, Content = file.Content };
            var blobResult = await client.Git.Blob.Create(owner, repoName, blob);
            newTreeItem.Add(new NewTreeItem
            {
                Path = file.FilePath.Replace("\\", "/"), // Ensure unix style paths
                Mode = "100644",
                Type = TreeType.Blob,
                Sha = blobResult.Sha
            });
        }

        // 5. Create a new tree
        var newTree = new NewTree { BaseTree = baseTreeSha };
        foreach(var item in newTreeItem) newTree.Tree.Add(item);
        var treeResult = await client.Git.Tree.Create(owner, repoName, newTree);

        // 6. Create a new commit
        var newCommit = new NewCommit(commitMessage, treeResult.Sha, baseBranchRef.Object.Sha);
        var commitResult = await client.Git.Commit.Create(owner, repoName, newCommit);

        // 7. Update the new branch reference to point to the new commit
        await client.Git.Reference.Update(owner, repoName, $"heads/{branchName}", new ReferenceUpdate(commitResult.Sha));

        // 8. Create a Pull Request
        var newPr = new NewPullRequest(commitMessage, branchName, baseBranch)
        {
            Body = "This PR was automatically generated by the .NET 8 Migration Dashboard."
        };
        var prResult = await client.PullRequest.Create(owner, repoName, newPr);

        return (branchName, prResult.HtmlUrl, commitResult.Sha);
    }

    public async Task<string> GetFileContentAsync(string token, string owner, string repoName, string path, string branchRef)
    {
        var client = GetClient(token);
        var contents = await client.Repository.Content.GetAllContentsByRef(owner, repoName, path, branchRef);
        return contents.Count > 0 ? contents[0].Content : string.Empty;
    }

    public async Task<PullRequest> GetPullRequestStatusAsync(string token, string owner, string repoName, int pullNumber)
    {
        var client = GetClient(token);
        return await client.PullRequest.Get(owner, repoName, pullNumber);
    }

    public async Task<PullRequestMerge> MergePullRequestAsync(string token, string owner, string repoName, int pullNumber, string mergeMethod, string? commitTitle = null)
    {
        var client = GetClient(token);
        var mergeMethodEnum = mergeMethod.ToLower() switch {
            "squash" => PullRequestMergeMethod.Squash,
            "rebase" => PullRequestMergeMethod.Rebase,
            _ => PullRequestMergeMethod.Merge
        };
        var merge = new MergePullRequest { MergeMethod = mergeMethodEnum };
        if (!string.IsNullOrEmpty(commitTitle)) {
            merge.CommitTitle = commitTitle;
        }
        return await client.PullRequest.Merge(owner, repoName, pullNumber, merge);
    }
    public async Task<CombinedCommitStatus> GetCombinedCommitStatusAsync(string token, string owner, string repoName, string sha)
    {
        var client = GetClient(token);
        return await client.Repository.Status.GetCombined(owner, repoName, sha);
    }
    
    public async Task DeleteBranchAsync(string token, string owner, string repoName, string branchName)
    {
        var client = GetClient(token);
        await client.Git.Reference.Delete(owner, repoName, $"heads/{branchName}");
    }

    public async Task<string?> FindRevertPullRequestAsync(string token, string owner, string repoName, int pullNumber)
    {
        var client = GetClient(token);
        
        // Use GetAllForRepository instead of Search API to avoid indexing delays
        var request = new PullRequestRequest
        {
            State = ItemStateFilter.All,
            SortProperty = PullRequestSort.Created,
            SortDirection = SortDirection.Descending
        };
        
        var apiOptions = new ApiOptions { PageCount = 1, PageSize = 30 };
        var prs = await client.PullRequest.GetAllForRepository(owner, repoName, request, apiOptions);
        
        var expectedBodyText = $"#{pullNumber}";
        
        foreach (var pr in prs)
        {
            if (pr.Title.StartsWith("Revert", StringComparison.OrdinalIgnoreCase) && 
               (pr.Body?.Contains(expectedBodyText) == true || pr.Head.Ref.Contains($"revert-") && pr.Head.Ref.Contains(pullNumber.ToString())))
            {
                return pr.HtmlUrl;
            }
        }
        return null;
    }

    public async Task<string> RevertPullRequestAsync(string token, string owner, string repoName, int pullNumber)
    {
        var pr = await GetPullRequestStatusAsync(token, owner, repoName, pullNumber);
        if (pr == null) throw new Exception("Pull request not found.");

        using var client = new HttpClient();
        client.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
        client.DefaultRequestHeaders.Add("User-Agent", _appName);
        
        var query = new {
            query = "mutation($input: RevertPullRequestInput!) { revertPullRequest(input: $input) { revertPullRequest { url } } }",
            variables = new {
                input = new {
                    pullRequestId = pr.NodeId
                }
            }
        };

        var content = new StringContent(System.Text.Json.JsonSerializer.Serialize(query), System.Text.Encoding.UTF8, "application/json");
        var response = await client.PostAsync("https://api.github.com/graphql", content);
        
        if (!response.IsSuccessStatusCode)
        {
            var err = await response.Content.ReadAsStringAsync();
            throw new Exception($"GraphQL error: {err}");
        }

        var json = await response.Content.ReadAsStringAsync();
        using var doc = System.Text.Json.JsonDocument.Parse(json);
        var root = doc.RootElement;
        
        if (root.TryGetProperty("errors", out var errors))
        {
            throw new Exception(errors[0].GetProperty("message").GetString());
        }

        return root.GetProperty("data")
                   .GetProperty("revertPullRequest")
                   .GetProperty("revertPullRequest")
                   .GetProperty("url")
                   .GetString() ?? "";
    }

    public async Task<string> GetRepositoryProfileAsync(string token, string owner, string repoName, string? targetBranch)
    {
        var client = GetClient(token);
        var repo = await client.Repository.Get(owner, repoName);
        var baseBranch = !string.IsNullOrEmpty(targetBranch) ? targetBranch : repo.DefaultBranch;
        var baseBranchRef = await client.Git.Reference.Get(owner, repoName, $"heads/{baseBranch}");

        var tree = await client.Git.Tree.GetRecursive(owner, repoName, baseBranchRef.Object.Sha);
        
        var csprojFiles = tree.Tree.Where(t => t.Path.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase)).ToList();
        var profiles = new List<object>();

        foreach (var file in csprojFiles)
        {
            try
            {
                var contentBytes = await client.Git.Blob.Get(owner, repoName, file.Sha);
                var xml = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(contentBytes.Content));

                var tfMatch = Regex.Match(xml, @"<TargetFramework>(.*?)</TargetFramework>");
                var tfsMatch = Regex.Match(xml, @"<TargetFrameworks>(.*?)</TargetFrameworks>");
                var sdkMatch = Regex.Match(xml, @"<Project\s+[^>]*Sdk=""([^""]+)""");

                var targetFramework = tfMatch.Success ? tfMatch.Groups[1].Value : (tfsMatch.Success ? tfsMatch.Groups[1].Value : "Unknown");
                var sdk = sdkMatch.Success ? sdkMatch.Groups[1].Value : "Microsoft.NET.Sdk";

                string projectType = "Class Library";
                if (sdk.Contains("Microsoft.NET.Sdk.Web")) projectType = "Web API / MVC";
                else if (xml.Contains("xunit") || xml.Contains("nunit") || xml.Contains("MSTest")) projectType = "Test Project";
                else if (Regex.IsMatch(xml, @"<OutputType>Exe</OutputType>")) projectType = "Console App";

                profiles.Add(new
                {
                    Path = file.Path,
                    TargetFramework = targetFramework,
                    ProjectType = projectType
                });
            }
            catch
            {
                // Ignore parse errors for individual files
            }
        }

        return System.Text.Json.JsonSerializer.Serialize(profiles, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
    }
}
